github.com:
    user: am-zest
    oauth_token: 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
    git_protocol: ssh
    users:
        am-zest:
            oauth_token: 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
