# zsh
ulimit -n 65535

# NPM
export NPM_PACKAGES="${HOME}/.npm-packages"

export PATH="$NPM_PACKAGES/bin:/usr/local/opt/openjdk@17/bin:/usr/local/opt/ruby/bin:/usr/local/opt/postgresql@15/bin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"
#
# cargo/rust
if [ -f "$HOME/.cargo/env" ]; then
  source "$HOME/.cargo/env"
fi

export PATH="$HOME/bin:$PATH"

# Preserve MANPATH if you already defined it somewhere in your config.
# Otherwise, fall back to `manpath` so we can inherit from `/etc/manpath`.
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"

##
# Your previous /Users/allenmyers/.zprofile file was backed up as /Users/allenmyers/.zprofile.macports-saved_2025-07-16_at_17:16:19
##

# MacPorts Installer addition on 2025-07-16_at_17:16:19: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# MacPorts Installer addition on 2025-07-16_at_17:16:19: adding an appropriate MANPATH variable for use with MacPorts.
export MANPATH="/opt/local/share/man:$MANPATH"
# Finished adapting your MANPATH environment variable for use with MacPorts.

